name: Toggle GitHub Actions

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Enable or Disable GitHub Actions'
        required: true
        default: 'enable'  # Default action

jobs:
  toggle-actions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run toggle actions script
      run: python toggle_actions.py ${{ github.event.inputs.action }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OWNER: 'repo_owner'
        REPO: 'repo_name'
